### ISSUE TITLE
Does Not Work in Safari

### ISSUE THREAD

**Issue by nathanlentz** [shavvimalND/fingerprint-browser#1]
`BrowserData` depends on at least one property that is not accessible in Safari (< Version 16.3)

Namely:
-  `screen.orientation.type`

According to [Can I Use](https://caniuse.com/?search=screen.orientation), `screen.orientation` is not available in versions of Safari older than 16.3

The [deployed demo](https://fingerprint-browser-next-js.vercel.app/) throws a client side exception in this version of Safari.

**Comment by shavtge** [comment]
Thanks for pointing this out. To make sure the `BrowserData` object doesn't fail anymore, I've added ternary checks to handle cases where some properties aren't available and default. i.e.:

```js
      ...
      orientation: screen.orientation ? screen.orientation.type : 'unknown',
      ...
      doNotTrack: window.navigator.doNotTrack !== undefined ? window.navigator.doNotTrack : 'unknown',
      hardwareConcurrency: window.navigator.hardwareConcurrency || 0,
      language: window.navigator.language,
      languages:  window.navigator.languages || [window.navigator.language],
      maxTouchPoints: window.navigator.maxTouchPoints || 0,
      userAgent: window.navigator.userAgent,
      pdfViewerEnabled: window.navigator.pdfViewerEnabled !== undefined ? window.navigator.pdfViewerEnabled : false,
      webdriver: window.navigator.webdriver !== undefined ? window.navigator.webdriver : false,
      ...
```
